version: '3.3'
services:
    postgres:
        container_name: party_db
        environment:
            - POSTGRES_USER=party_svc
            - POSTGRES_PASSWORD=party_svc
            - POSTGRES_DB=party_svc
        ports:
            - '5432:5432'
        image: 'postgres:14.1'