version: '3.3'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - QUARKUS_SERVER_ADDR1=quarkus-1:8888
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - quarkus-1
      
  quarkus-1:
    build:
      context: be-service-partyplanner
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - postgres
      
  postgres:
    container_name: party_db
    environment:
        - POSTGRES_USER=party_svc
        - POSTGRES_PASSWORD=party_svc
        - POSTGRES_DB=party_svc
    ports:
        - '5432:5432'
    image: 'postgres:14.1'